export const products = [
    {
      id: 1,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/instant_jars_image_1_1_-min.png?v=1746614741",
      title: "100% Arabica Instant Coffee",
      description: "Rich flavour and genuine aroma, brews within seconds.",
      price: "729",
      tags: ["Real good coffee", "Ready in seconds"],
      buttonText: "Shop Now",
    },
    {
      id: 2,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Frame_3-min.png?v=1746617371",
      title: "Cold Brew Bottle (Classic)",
      description: "Signature Cold Brew with milk & a little sugar — strong, refreshing and preservative‑free.",
      price: "1059",
      tags: ["Chilled & ready", "Strong coffee flavor"],
      buttonText: "Buy Bottle",
    },
    {
      id: 3,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Hot_Brew_img.png?v=1641798896",
      title: "Hot Brew Coffee Bags",
      description: "5‑minute brew-ready bags made from 100% Arabica—same flavour as ground coffee.",
      price: "475",
      tags: ["Dip & sip", "Grade‑A Arabica"],
      buttonText: "Buy Hot Brew",
    },
    {
      id: 4,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Bottles_img.png?v=1641799163",
      title: "Cold Brew Bottle (Hazelnut/Salted Caramel/Vanilla/Mocha)",
      description: "Iced coffee bottle with OG Cold Brew, milk & sugar, available in flavored variants.",
      price: "1059",
      tags: ["Flavoured", "Under 100 calories"],
      buttonText: "Grab Flavour",
    },
    {
      id: 5,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Frame_3_1_-min.png?v=1746618105",
      title: "Cold Brew Bottle (Assorted Flavours)",
      description: "Packaged bottle set with a variety of ready-to-drink Cold Brew flavours.",
      price: "2999",
      tags: ["Assorted pack", "Break‑proof shipping"],
      buttonText: "Shop Assorted",
    },
    {
      id: 6,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Frame_4-min.png?v=1746618490",
      title: "Coffee Beans / Ground Coffee",
      description: "Grade‑A Arabica beans—Dark Roast, French Vanilla, Hazelnut, Original.",
      price: "499",
      tags: ["Whole beans", "Freshly sealed"],
      buttonText: "Buy Beans",
    },
    {
      id: 7,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Coffee_Beans_img.png?v=1641799641",
      title: "Hot Brew Bags (Dark Roast)",
      description: "Chocolatey & toasty dark roast in convenient brew bags.",
      price: "350",
      tags: ["Bold flavour", "High caffeine"],
      buttonText: "Buy Dark Brew",
    },
    {
      id: 8,
      image: "https://cdn.shopify.com/s/files/1/1308/0907/files/Group_3346_2_-min.png?v=1746619578",
      title: "Hot Brew Bags (Pumpkin Spice)",
      description: "Seasonal blend of clove, nutmeg, cinnamon—limited edition.",
      price: "300",
      tags: ["Spiced", "Limited edition"],
      buttonText: "Buy Pumpkin",
    },
  ]